---
- name: "Get NodeJS v13 from source"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      
- name: "Install NodeJS v13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install pm2 globally - process mgr for prod Node.js app"
  npm:
    name: pm2
    global: yes
    production: yes

- name: "Move evn variables to /etc/profile.d"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d